### ISSUE TITLE
Plugins error

### ISSUE THREAD

**Issue by Malex** [Malex/FrozenFW#2]
When an exception is raised from a function in Dispatcher list, its ouput will be 
Traceback (most recent call last):
  File "/usr/lib64/python3.1/site-packages/frozen-2.0_alpha-py3.1.egg/frozen/wsgi/init.py", line 6, in app
    rep_status,headers,body, filename = dispatch((conf.query("base_dir")+data.SERVER['PATH_INFO']).replace("//","/"))
  File "/usr/lib64/python3.1/site-packages/frozen-2.0_alpha-py3.1.egg/frozen/Dispatcher.py", line 59, in **call**
    return self.check()
  File "/usr/lib64/python3.1/site-packages/frozen-2.0_alpha-py3.1.egg/frozen/Dispatcher.py", line 64, in check
    t2 = i(*tmp)
  File "<string>", line {}, in {function}

followed by error.
This causes time lost in checking what plugin defines that function.
It should be avoided by using a user-defined callable object (instead of simple functions) which saves the file.

**Comment by Malex** [comment]
It's quite difficul to solve this issue, since in Plugins.py I use sandbox, so the file is loaded by sandbox object and thus I have no control about what is actually happening there. I can only check during plugins loading, I can't catch exception raised only at dispatching time.

**Comment by Malex** [comment]
Actually, it does not specify which file define the function above, but, at least, it does not write useless traceback in logs asd.

**Comment by Malex** [comment]
Could be solved by addind an object instead of a simple function in Plugins

**Comment by Malex** [comment]
Restyling in 2.1 should resolve it completely. 'til then, I reopen the issue.
